project:
  type: website
  output-dir: docs

website:
  title: "BIB18"
  navbar:
    left:
      - href: index.qmd
        text: About
      - titles.ipynb
      - collaborations.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Code"



