project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!readme.md"

website:
  title: "BIB18"
  navbar:
    left:
      - href: index.qmd
        text: About
      - time.ipynb
      - types.ipynb
      - people.ipynb
      - publishers.ipynb
      - titles.ipynb
      - languages.ipynb
      - collaborations.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Code"



