project:
  type: website
  output-dir: docs

website:
  title: "BIB18"
  navbar:
    left:
      - href: source/index.qmd
        text: Home
      - source/titles.ipynb
      - source/collaborations.ipynb

format:
  html:
    theme: cosmo
    css: source/styles.css
    toc: true
    code-fold: true
    code-summary: "Code"



