project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!readme.md"

website:
  title: "BIB18"
  page-footer: "Christof Schöch, 2024, CC BY" 
  navbar:
    left:
      - href: index.qmd
        text: About
      - time.ipynb
      - types.ipynb
      - people.ipynb
      - publishers.ipynb
      - titles.ipynb
      - languages.ipynb
      - coeditors.ipynb
      - coauthors.ipynb
    tools:
      - icon: github
        menu:
          - text: Source
            url:  https://github.com/christofs/BIB18
          - text: Issues
            url:  https://github.com/christofs/BIB18/issues

format:
  html:
    theme:
      light: flatly
      dark: darkly    
    css: styles.css
    toc: false
    code-fold: true
    code-summary: "Code"



