---
title: "BIB18"
---

Website containing data and analyses of the dataset derived from the *Bibliographie sur le XVIIIe siècle*. 

## Orientation 

Source of the data: Benoît Melançon, for background information see [mapageweb.umontreal.ca/melancon/donnees_biblios_1_550.html](http://mapageweb.umontreal.ca/melancon/donnees_biblios_1_550.html) and for the Dataverse deposit, see [doi.org/10.5683/SP3/PYYEEH](https://doi.org/10.5683/SP3/PYYEEH). 

For more information on the transformation process, and to obtain the dataset in various formats (BibTeX, Zotero RDF, JSON), see: [github.com/christofs/BIB18](https://github.com/christofs/BIB18). The transformation was performed in May 2023. 

The resulting bibliography can be consulted on Zotero, see: [zotero.org/groups/5067408/BIB18](https://www.zotero.org/groups/5067408/BIB18).

Some analyses of the dataset are available on the present website. The scripts to create the analyses and generate the website pages is also available at [github.com/christofs/BIB18](https://github.com/christofs/BIB18). 

## Nota bene

Benoît Melançon specifies: "Quiconque souhaite s’approprier ces données peut le faire, sous deux conditions. 1. L’attribution de la collecte des données doit toujours être rappelée, par exemple sous la forme «Données colligées par Benoît Melançon». 2. Aucune exploitation commerciale de ces données n’est tolérée. Elles ne peuvent pas être vendues sous quelque forme que ce soit. Autrement dit, chez Creative Commons : Attribution-NonCommercial 4.0 International (CC BY-NC 4.0) — [https://creativecommons.org/licenses/by-nc/4.0/](https://creativecommons.org/licenses/by-nc/4.0/)."